### ISSUE TITLE
Switch to using SQLite to lower memory usage

### ISSUE THREAD

**Issue by lucashuy** [itslupus/burntbot#17]
Improve bot memory usage by using SQLite to save data instead of writing to a regular file. This has the added benefit of asking the database for data instead of keeping literally everything in RAM.

**Comment by redviking1** [comment]
This is a good idea.  Where does burntbot presently store user profile and transaction data?

**Comment by lucashuy** [comment]
The transaction data is loaded on start up and stored temporarily in RAM. The user data (user ID, session token, etc) is stored in the `.persistence` file which is just JSON data.

Part of the reason why I want to switch to something like SQLite is that when designing the ignore feature of the list, it became clear that managing things like position and ignore values for users on the list was beginning to stretch the usability of the existing bandaid solution.

Saving modified data involved rewriting the entire file, as you can probably guess is a taxing operation. Additionally, with everything loaded into RAM, RAM usage is starting to get higher than I'd like it to be.

The plan is to move anything that is stored in RAM currently (transaction history, list data) and move it to SQLite.

**Comment by redviking1** [comment]
SQLite is a great choice because it is small, fast, mostly standard compliant (except many functions), mature, hugely popular, and Python has a "built-in" `sqlite` library.  My only complaint with SQLite is that it doesn't enforce column types, but Python doesn't have static data types, either, so I guess that makes them good companions.

**Comment by redviking1** [comment]
> The plan is to move anything that is stored in RAM currently (transaction history, list data) and move it to SQLite.

Do you store the full transaction history in RAM or just the daily transactions?  You could discard the transaction history after you've calculated the current debit and credit balance (or even just the net balance) for each peer.

**Comment by lucashuy** [comment]
> 
> 
> > The plan is to move anything that is stored in RAM currently (transaction history, list data) and move it to SQLite.
> 
> Do you store the full transaction history in RAM or just the daily transactions? You could discard the transaction history after you've calculated the current debit and credit balance (or even just the net balance) for each peer.

I currently store all previous transaction IDs (not the full transaction object) to cross reference in case the API returns faulty data. 

It wasn't like this before. At some point I changed it to only save the timestamp of the most recent transaction per user and cross check against that. This lead to double sends for some reason though. I had then reverted the code to the same code I ran mid-May, which at this point was tried and tested.

The downside to storing all the IDs in RAM (and is the reason why I want to get away from this) is the space required to store tens of thousands of unique strings since variables in Python are encapsulated. The string `TI_ELKA8TJUA5VDT28` for example takes 67 bytes on my system.

In any case, the new system will store that transaction data in the database, eliminating the need for fetching history after each reboot.

**Comment by redviking1** [comment]
Another good data store option might be [LMDB](https://en.wikipedia.org/wiki/Lightning_Memory-Mapped_Database).

**Comment by lucashuy** [comment]
> 
> 
> Another good data store option might be [LMDB](https://en.wikipedia.org/wiki/Lightning_Memory-Mapped_Database).

Interesting, but from first glance it looks like a key/value store instead of a traditional relational database. While using something like `lmdb` would effectively not change the flow of how the bot currently works, I think I would rather use SQL to manipulate data (eg `SUM(column)` with SQL vs getting all keys and adding in Python). I'm willing to take whatever performance hit there might be for that.

**Comment by derekmahar** [comment]
Yes, it's precisely a key-value store.  I guess your choice would depend on what you want to model.  I imagine some of the data would be simple key-values, while the rest might be more relational.

**Comment by lucashuy** [comment]
> 
> 
> I imagine some of the data would be simple key-values, while the rest might be more relational.

Speaking of which, the bot does contain some key/value pairs that would make sense storing in lmdb. Things like persistent bot settings (privacy options, return notes, poll rates) would be great to store in something like this, but getting users to install another data management system just for that seems a bit extreme in my mind.

**Comment by derekmahar** [comment]
Maybe it makes sense to still store some of these in text files that users could more easily edit.

**Comment by lucashuy** [comment]
> 
> 
> Maybe it makes sense to still store some of these in text files that users could more easily edit.

Yeah thats probably a good idea (better than what I was going to do).
