### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'isoformat'

### ISSUE THREAD

**Issue by alexs00001** [itslupus/burntbot#21]
Reinstalled following a crash and I'm unable to start the bot now. Need some advice. Tried reinstalling python. I get the same behaviour using 3.9 and 3.10.

  File "/Users/alexs001/Downloads/burntbot-master/classes/bot.py", line 112, in run
    'since': self.recent_transaction_datetime.isoformat()
AttributeError: 'NoneType' object has no attribute 'isoformat'

**Comment by lucashuy** [comment]
Thanks for bringing this up, I'll investigate this issue further.

**Comment by alexs00001** [comment]
Cheers. Let me know if I can supply any other pertinent details.

**Comment by lucashuy** [comment]
I'm not able to reproduce this issue running Python 3.8.10 with burntbot 0.9.3.

Have you ever made a peer to peer transaction with Shakepay in Canadian dollars? I have a feeling that might be the reason why it is not working since it is trying to get the most recent P2P transaction you've made, but none exists.

**Comment by alexs00001** [comment]
I have not. The bot has served solely to keep my shaking streak alive when I travel. This didn't seem to be a problem previously.

**Comment by lucashuy** [comment]
Awesome, thanks for clearing it up. I've updated the file in question to resolve that issue. Let me know if that fixes it for you and then I can close up this issue.

**Comment by alexs00001** [comment]
Success. Thanks for the quick response!

**Comment by lucashuy** [comment]
You're welcome, feel free to reopen or create a new issue if there is anything else that broke.
