### ISSUE TITLE
New IP verification before login

### ISSUE THREAD

**Issue by lucashuy** [itslupus/burntbot#3]
Shakepay has a (new?) IP verification where the user must click a link in an email before they can login on a new IP address.
Not sure how the login process has changed for this and if the bot can handle it.

**Comment by idjmic** [comment]
Mine is still working, I did do the email process to authenticate my IP though.

**Comment by lucashuy** [comment]
It seems that you may have gotten lucky, there have been two new people that tried to login and have failed due to how the bot authenticates the old way. This is now at the top of the list of things I should complete.
